### ISSUE TITLE
Teleporter command not working?

### ISSUE THREAD

**Issue by Slendykins** [Higgins4k/BetterTerminal#6]
Hey again! Been using the mod quite a bit but I rarely get time as the "terminal guy",

Of all the commands i've been using they all work wonders, apart from Teleport/TP,

I was watching my friend on the terminal and attempting to teleport save from a giant... it used the inverse teleporter?

I was trying to test it the next again day but it just kept wanting to use the inverse teleporter, still gave the message for using the TP rather than the unique one from the ITP making me think there was some sort of conflict with what was being called?

**Comment by Higgins4k** [comment]
Hey, can I get a list of mods that you have installed? I was unable to recreate this so I will take a look and see what the issue could be conflicting and fix it

**Comment by Slendykins** [comment]
Hey of course,

I'm not sure how to export the mod list in text but here's the code - 018d139d-f5e7-bf9a-c178-bee5d38a32ae

The only mod i'd suspect to cause a conflict here is BetterTeleporter but even with that disabled it spins up the ITP

**Comment by SkyeAveragejoe** [comment]
ive got the same issue, when i run tp command the inverse fires up.
this is my mod list, just in case there are any overlaps with the OP's list
018d13b0-b7c4-f0f3-1c12-0190d1d292fa

**Comment by Slendykins** [comment]
Just had a look to cross reference any mods that could be causing problems, 

- Runtime_Netcode_Patcher
- ReservedItems
- More_Suits

I've tested my save with all of these disabled but still no dice, it keeps wanting to use ITP

**Comment by bozeeetopic** [comment]
I have a different bug but falls in same category. The added command Inverse messes up the purchase of the inverse teleporter command. So on a new save, when typing Inverse in terminal, I get a message that i don't own an inverse teleporter so i can't use it, but I can't buy it either. Tried it with just this mod and still didn't work. Perhaps change the command to inverset just to not override the buy one, or make it so that you buy the inverse the first time you run the command and afterwards to actually use it. Anyways great mod, appreciate you, keep up the good work! :)

**Comment by Higgins4k** [comment]
Okay will be reworking the teleport commands and have a update fixing both these tonight

**Comment by Higgins4k** [comment]
@bozeeetopic @Slendykins @SkyeAveragejoe All these issues are fixed and will be pushed on Thunderstore soon under 1.1.1, if downloading manually wait till I've marked this as complete to make sure GitHub version number is correct 

Thanks for the reports! Make another issue with any suggestions or bugs
